### ISSUE TITLE
Additional padding in footer (Firefox)

### ISSUE THREAD

**Issue by newswim** [5calls/5calls#399]
Hey 5Calls :)

I noticed when viewing the site in Firefox, there is some additional vendor styling which makes the footer look wonky.

<img width="1446" alt="screen shot 2018-05-21 at 5 26 19 pm" src="https://user-images.githubusercontent.com/6667096/40333311-7a9befae-5d1d-11e8-82f3-ebcdcef54aba.png">

This can be remedied by removing all padding

```css
footer .colophon ul {
    ...
    padding: 0;
}
```
